# Generated by Django 3.2.8 on 2022-04-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['rating']},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, default='res', max_length=100),
        ),
    ]
