# Generated by Django 3.2.8 on 2021-12-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/foods/', verbose_name='food_image'),
        ),
    ]
