# Generated by Django 3.2.8 on 2022-01-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20220101_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
