# Generated by Django 3.2.8 on 2022-01-11 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0006_auto_20220103_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='review',
            new_name='star',
        ),
        migrations.RemoveField(
            model_name='food',
            name='num_review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='food',
        ),
        migrations.AddField(
            model_name='food',
            name='try_it',
            field=models.ManyToManyField(blank=True, related_name='try_it', to=settings.AUTH_USER_MODEL),
        ),
    ]
