# Generated by Django 3.2.8 on 2022-01-13 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0008_auto_20220112_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='_restaurants_restaurant_like_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
