# Generated by Django 3.2.8 on 2022-01-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20220116_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='review',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='num_reviews',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='restaurants.Review'),
        ),
    ]
