# Generated by Django 3.2.8 on 2021-12-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogpage_options'),
        ('user', '0003_userprofile_additional_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='collections',
            field=models.ManyToManyField(null=True, related_name='collection', to='blog.BlogPage'),
        ),
    ]
