# Generated by Django 3.2.8 on 2021-12-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogpage_options'),
        ('user', '0004_userprofile_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collection', to='blog.BlogPage'),
        ),
    ]
