# Generated by Django 3.2.8 on 2021-12-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_user_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ['-date']},
        ),
    ]
