# Generated by Django 3.2.8 on 2022-01-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
