# Generated by Django 3.2.8 on 2022-01-06 00:02

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20220105_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='category', to='blog.BlogCategory'),
        ),
    ]
