# Generated by Django 3.2.8 on 2022-01-10 06:51

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20220106_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
