# Generated by Django 3.2.8 on 2022-01-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20220110_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
